#!/bin/sh

BASE=$HOME/Maildir
ARCHIVEBASE=$HOME/Maildir

for folder in `find $BASE -regextype posix-extended  -maxdepth 1 -type d \! -iregex ".*\.archiv(\..*)?" \! -name cur \! -name tmp \! -name new \! -name search \! -regex '.*\.SPAM.*' \! -name "courier*"`
do
  folder=$(basename $folder)
  if [ "${folder}" = "Maildir" ]; then folder=INBOX; fi
  ./cleanup-maildir.py --archive-subfolder=archiv --maildir-root=$BASE --folder-prefix="" --age=90 -d 2 -k -u -v archive ${folder} > logfile.txt
done
